name: Auto Close

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-close:
    name: Auto Close
    runs-on: ubuntu-latest

    steps:
      - name: Auto close issues with invalid templates
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body?.toLowerCase() || '';
            
            // Check for spam or invalid issues
            const spamKeywords = ['spam', 'test', 'testing', 'hello', 'hi', 'hey'];
            const isSpam = spamKeywords.some(keyword => 
              title.includes(keyword) || body.includes(keyword)
            );
            
            // Check for empty or very short issues
            const isEmpty = body.length < 10;
            
            // Check for issues that don't follow the template
            const hasTemplate = body.includes('##') && body.includes('###');
            
            if (isSpam || isEmpty || !hasTemplate) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `## ❌ Issue Fechada Automaticamente

Este issue foi fechado automaticamente porque:

${isSpam ? '- Contém palavras-chave de spam\n' : ''}${isEmpty ? '- Está vazio ou muito curto\n' : ''}${!hasTemplate ? '- Não segue o template de issue\n' : ''}

Por favor, abra um novo issue seguindo o template correto. Obrigado!`
              });
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed',
                labels: ['invalid', 'spam']
              });
            }

      - name: Auto close pull requests with invalid templates
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.toLowerCase();
            const body = pr.body?.toLowerCase() || '';
            
            // Check for spam or invalid PRs
            const spamKeywords = ['spam', 'test', 'testing', 'hello', 'hi', 'hey'];
            const isSpam = spamKeywords.some(keyword => 
              title.includes(keyword) || body.includes(keyword)
            );
            
            // Check for empty or very short PRs
            const isEmpty = body.length < 10;
            
            // Check for PRs that don't follow the template
            const hasTemplate = body.includes('##') && body.includes('###');
            
            if (isSpam || isEmpty || !hasTemplate) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `## ❌ Pull Request Fechado Automaticamente

Este PR foi fechado automaticamente porque:

${isSpam ? '- Contém palavras-chave de spam\n' : ''}${isEmpty ? '- Está vazio ou muito curto\n' : ''}${!hasTemplate ? '- Não segue o template de PR\n' : ''}

Por favor, abra um novo PR seguindo o template correto. Obrigado!`
              });
              
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
            }

